### ISSUE TITLE
I need to call new activity after 100% bootstrap

### ISSUE THREAD

**Issue by AdhithAdhi** [05nelsonm/TorOnionProxyLibrary-Android#109]
what is the code for calling  other functions or activities after 100% bootstrap.
where do I need to write calls or function. 
help me am new to android studio but I know Xamarin. please help me

**Comment by 05nelsonm** [comment]
That will be broadcast to the <a href="https://github.com/05nelsonm/TorOnionProxyLibrary-Android/blob/445deda0d67035417955321634b49364f797256a/topl-core-base/src/main/java/io/matthewnelson/topl_core_base/EventBroadcaster.kt#L135" target="_blank">EventBroadcaster.broadcastNotice</a> that you set in the builder.

It will look something like this:
```kotlin
NOTICE|BaseEventListener|Bootstrapped 5% (conn): Connecting to a relay
```

You can listen for it there.
